### PR TITLE
Update CHI-2015-VasilescuPRBSDF.json

### PR DESCRIPTION
**Pull request by aserebrenik**

### CODE REVIEW

**Comment by grammarware** [comment]
Tagged 68 files total with “gender” and similar words, see commit [`968ef529`](https://github.com/slebok/bibsleigh/commit/968ef52903c963a08fcff7980db14744be981eff).

**Comment by aserebrenik** [comment]
Nice! BTW, I'm not sure that GitHub and Git should be together...

---

Van: Vadim Zaytsev [notifications@github.com]
Verzonden: woensdag 9 december 2015 14:56
Aan: slebok/bibsleigh
CC: Serebrenik, A.
Onderwerp: Re: [bibsleigh] Update CHI-2015-VasilescuPRBSDF.json (#3)

Tagged 68 more files with “gender” and similar words, see commit 968ef529https://github.com/slebok/bibsleigh/commit/968ef52903c963a08fcff7980db14744be981eff.

**Comment by grammarware** [comment]
BTW, @aserebrenik, did you find the auto-stemming feature? I’ve added it after SATToSE, for an example see [gender](http://bibtex.github.io/word/gender.html).

**Comment by aserebrenik** [comment]
I've seen it but I'm not sure whether I like it: as any automatic approach it might introduce imprecision, e.g., keecl, fsmdas do not seem to be useful words. I wonder whether the stemmer can be improved somehow...

---

Van: Vadim Zaytsev [notifications@github.com]
Verzonden: woensdag 9 december 2015 15:07
Aan: slebok/bibsleigh
CC: Serebrenik, A.
Onderwerp: Re: [bibsleigh] Update CHI-2015-VasilescuPRBSDF.json (#3)

BTW, @aserebrenikhttps://github.com/aserebrenik, did you find the auto-stemming feature? I’ve added it after SATToSE, for an example see genderhttp://bibtex.github.io/word/gender.html.

**Comment by grammarware** [comment]
That’s why I don’t give up on tags: they can be much more precise, multi-match on different representations including even running arbitrary regexps, and group related terms in their definition.

As far as I understand, stemming can be pushed farther only to lemmatisation, as well as rely on blacklists and whitelists to cover corner cases. It will anyhow stay a semi-reliable fully automatic heuristic.

**Comment by aserebrenik** [comment]
Sure. I still wonder whether NER-type tooling can improve the heuristics.

---

Van: Vadim Zaytsev [notifications@github.com]
Verzonden: woensdag 9 december 2015 15:30
Aan: slebok/bibsleigh
CC: Serebrenik, A.
Onderwerp: Re: [bibsleigh] Update CHI-2015-VasilescuPRBSDF.json (#3)

That’s why I don’t give up on tags: they can be much more precise, multi-match on different representations including even running arbitrary regexps, and group related terms in their definition.

As far as I understand, stemming can be pushed farther only to lemmatisation, as well as rely on blacklists and whitelists to cover corner cases. It will anyhow stay a semi-reliable fully automatic heuristic.

**Pull request merged**
